Estandarizacion de agregarReceta y modificarPassword
Nervios-de-Acero/tesis-avocado pull request #55
Opened 2024-05-05 04:01 UTC by HernanRT

2024-05-05 04:26 UTC, Loreaylen requested changes
Está todo bastante bien. Fijate porfa de resolver lo que marqué, algunas cosas son de jodida nomás pero lo de los cambios es importante.

2024-05-05 04:26 UTC, Loreaylen commented on backend/controllers/recetaController.js
> +        const db = require('../conection');
La conexión a la DB, las funcionesComunes y el controller están definidos al principio del archivo. Eliminar estos.

2024-05-05 04:26 UTC, Loreaylen commented on backend/controllers/recetaController.js
> +        typeof req.body.titulo == 'undefined' ||
Toda esta lógica se puede mover al archivo de validaciones que se usa con checkSchema (en este caso sería validacionesRecetas.js). Entiendo que es "exists" 
https://express-validator.github.io/docs/api/validation-chain/#exists

Fijate que en la ruta se devuelva un 400 siempre que haya un error de validación. Ojo que va a devolver un array de errores.

2024-05-05 04:26 UTC, Loreaylen commented on backend/controllers/usuarioController.js
> +<<<<<<< Updated upstream
Guarda que te quedaron las marcas de los cambios. En el visual te aparece el current change y el incoming change, tenés que aceptar alguno.

2024-05-05 04:26 UTC, Loreaylen commented on backend/controllers/usuarioController.js
> +        if (!email || !pass || !nuevoPass) {
Lo mismo que para las recetas, fijate si esto se puede mover al archivo validacionesPassword.

2024-05-07 00:18 UTC, HernanRT reviewed
Corregidos. Hago un nuevo pr.

2024-05-10 00:36 UTC, closed without merging